config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :order_items
  resources :carts 
  resources :courses do
   resources :videos
  end
  root 'courses#home'
  get 'carts/show'
  get '/courses/my_enroll/:id', to: 'courses#create', as:'enroll_regist'
  get '/courses/enroll/:id', to: 'enrollments#create', as:'enroll_course'
  get 'cart/checkout', to:'carts#checkout', as:'checkout'
  post 'courses/add_to_cart/:id', to:'courses#add_to_cart', as: 'add_to_cart'
  delete 'courses/remove_from_cart/:id', to:'courses#remove_from_cart', as:'remove_from_cart'
  devise_for :users
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :course
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
    def index
        @course=Course.find(params[:course_id])
        @videos=@course.videos
      end
      def new
        @course=Course.find(params[:course_id])
        @video = @course.videos.new
      end
      def edit
        @course=Course.find(params[:course_id])
        @video=@course.videos.find(params[:id])
      end
      def show
        @course=Course.find(params[:course_id])
        @video=@course.videos.find(params[:id])
      end
      def create
          @course=Course.find(params[:course_id])
          @video = @course.videos.create(video_params)
          # session[:course_id] = @course.id
          if @video.save
           redirect_to course_path(@course)
          end
      end
      def update
          @course=Course.find(params[:course_id])
          @video = @course.videos.find(params[:id])
          @video.update_attributes(video_params)
          @video = current_course.videos
          redirect_to @video
      end
      
      def destroy
        @course = Course.find(params[:course_id])
        @video = @course.videos.find(params[:id])
        @video.destroy
        redirect_to course_path(@course)
        # @video = current_course.videos
      end
      private
        def video_params
          params.require(:video).permit(:title,:url,:course_id)
        end
      
        def set_order
          @course = current_course
        end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_foot.html.erb
<div class="bg-dark col-13 offset-0" style="padding-bottom:1rem; padding-top:0rem;margin-top:24rem">
  <footer class="py-5 px-5 mt-5 pb-0" >
    <div class="row">
        <h5 style="color:white">Top companies choose <%= link_to "Udemy Business", root_path%> to build in-demand career skills.</h5>
    </div>

    <div class="d-flex justify-content-between py-4 my-4 border-top" >
    <div class="col-2" style="color:white">
        <ul class="nav flex-column" style="color:white">
          <li class="nav-item mb-2"><a href="#" style="color:white" class="nav-link p-0 ">Udemy Business</a></li>
          <li class="nav-item mb-2"><a href="#" style="color:white" class="nav-link p-0 ">Teach on Udemy</a></li>
          <li class="nav-item mb-2"><a href="#" style="color:white" class="nav-link p-0 ">Get the app</a></li>
          <li class="nav-item mb-2"><a href="#" style="color:white" class="nav-link p-0 ">About us</a></li>
          <li class="nav-item mb-2"><a href="#" style="color:white" class="nav-link p-0">Contact us</a></li>
        </ul>
      </div>

      <div class="col-2">
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" style="color:white" class="nav-link p-0 ">Careers</a></li>
          <li class="nav-item mb-2"><a href="#" style="color:white" class="nav-link p-0 ">Blog</a></li>
          <li class="nav-item mb-2"><a href="#" style="color:white" class="nav-link p-0 ">Help and Support</a></li>
          <li class="nav-item mb-2"><a href="#" style="color:white" class="nav-link p-0 ">Affiliate</a></li>
          <li class="nav-item mb-2"><a href="#" style="color:white" class="nav-link p-0 ">Investors</a></li>
        </ul>
      </div>

      <div class="col-2">
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" style="color:white" class="nav-link p-0 ">Terms</a></li>
          <li class="nav-item mb-2"><a href="#" style="color:white" class="nav-link p-0 ">Privacy Policy</a></li>
          <li class="nav-item mb-2"><a href="#" style="color:white" class="nav-link p-0 ">Sitemap</a></li>
          <li class="nav-item mb-2"><a href="#" style="color:white" class="nav-link p-0 ">Accessibility Statements</a></li>
        </ul>
      </div>
      <div class="col-4 offset-5 text-decoration-none">
        <form>
          <div class="">
            <button class="btn rounded-0 border-light btn-outline-secondary text-decoration-none" type="button" style="color:white">Subscribe</button>
          </div>
        </form>
      </div>
      <%
=begin%>
 <p>© 2021 Company, Inc. All rights reserved.</p>
      <ul class="list-unstyled d-flex">
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
      </ul> 
<%
=end%>
    </div>
  </footer>
</div>

app/views/videos/_form.html.erb
<%= form_with model: [@course, @course.videos.build] do |form| %>
<div class="field btn-lg d-grid col-md-3 offset-md-4" style="text-align:center">
<div class="border border-dark border-1 ml-2 mb-2">
  <div>
    <%= form.text_field :title,placeholder: "Title", autofocus: true, autocomplete: "Title",class:"text-decoration-none shadow-none col-md-12 offset-md-0 ps-2 fs-5"%>
  </div>
</div>
<div class="border border-dark border-1 ml-2 mb-2">
    <div>
    <%= form.text_field :url ,placeholder: "URL", autofocus: true, autocomplete: "URL",class:"text-decoration-none shadow-none col-md-12 offset-md-0 ps-2 fs-5"%><br>
  </div>
</div>  
  <div>
    <h2><%= form.submit class:"btn-group  btn-primary btn-group-lg ms-2"%></h2>
  </div>
  <ul>
  <%= link_to "Home", root_path, class:"btn btn-primary"%>
  </ul>
  </div>
<% end %>

app/views/videos/_nav.html.erb
<% if user_signed_in? %>
<% if current_user.user_role.downcase == "student"%>
<nav class="navbar navbar-expand-lg d-flex navbar-light bg-white shadow p-3 mb-4 bg-body rounded">
  <div class="container-fluid mt-0">
    <h1 class="navbar-brand fw-bold" href="#"><%= link_to "UdemyClone", root_path , class:"text-decoration-none ", style:"color:black"%></h1>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Categories</a>
        </li>
        <form class="d-flex">
        <input class="input-group border-dark me-auto mb-0 rounded-pill" style="padding-right:21rem; padding-left:2rem" type="search" placeholder="Search for anything" aria-label="Search" >
      </form>
      </ul>
      <ul class="navbar-nav me-0 mb-2 mb-lg-0">
        <li class="nav-item me-1">
          <a class="nav-link active" aria-current="page" href="#">Udemy Business</a>
        </li>
        <li class="nav-item me-1">
          <a class="nav-link active" aria-current="page" href="#">Teach on Udemy</a>
        </li>
        <li class="nav-item me-1 mt-2">
         <%= link_to "My Learning", courses_path, class:"text-decoration-none ", style:"color:black"%>
        </li>
        <li class="nav-item me-3 ms-2 mt-2">
        <%= link_to "Cart",carts_show_path ,class:"text-decoration-none",style:"color:black"%>
        <%
=begin%>
 <svg xmlns="http://www.w3.org/2000/svg" width="20" height="40" fill="currentColor" class="bi bi-cart3 me-2" viewBox="0 0 16 16">
  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
</svg> 
<%
=end%>
        </li>
        
        <li class="nav-item me-2">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%
=begin%>
 <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-person-circle pe-2" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg> 
<%
=end%>
           <button class="btn btn-dark" type="button">
           
           <%= link_to current_user.name, destroy_user_session_path, method: :delete ,class:"text-decoration-none", style:"color:white"%>
          </button>
        </div>
        </li>
        <% elsif current_user.user_role.downcase == "instructor"%>
  <nav class="navbar navbar-expand-lg d-flex navbar-light bg-white shadow p-3 mb-4 bg-body rounded">
  <div class="container-fluid mt-0">
    <h1 class="navbar-brand fw-bold" href="#"><%= link_to "UdemyClone", root_path , class:"text-decoration-none ", style:"color:black"%></h1>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Categories</a>
        </li>
        <form class="d-flex">
        <input class="input-group border-dark me-auto mb-0 rounded-pill" style="padding-right:21rem; padding-left:2rem" type="search" placeholder="Search for anything" aria-label="Search" >
      </form>
      </ul>
      <ul class="navbar-nav me-0 mb-2 mb-lg-0">
        <li class="nav-item me-1">
          <a class="nav-link active" aria-current="page" href="#">Udemy Business</a>
        </li>
        <li class="nav-item me-1">
          <a class="nav-link active" aria-current="page" href="#">Teach on Udemy</a>
        </li>
        <li class="nav-item me-3 ms-2 mt-2">
        <%= link_to "My Course",courses_path ,class:"text-decoration-none",style:"color:black"%>
        <%
=begin%>
 <svg xmlns="http://www.w3.org/2000/svg" width="20" height="40" fill="currentColor" class="bi bi-cart3 me-2" viewBox="0 0 16 16">
  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
</svg> 
<%
=end%>
        </li>
        
        <li class="nav-item me-2">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%
=begin%>
 <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-person-circle pe-2" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg> 
<%
=end%>
           <button class="btn btn-dark" type="button">
           
           <%= link_to current_user.name, destroy_user_session_path, method: :delete ,class:"text-decoration-none", style:"color:white"%>
          </button>
        </div>
        </li>
        <% end %>
        <% else %>
        <nav class="navbar navbar-expand-lg d-flex navbar-light bg-white shadow p-3 mb-4 bg-body rounded">
  <div class="container-fluid mt-0">
    <h1 class="navbar-brand fw-bold" href="#"><%= link_to "UdemyClone", root_path , class:"text-decoration-none", style:"color:black"%></h1>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Categories</a>
        </li>
        <form class="d-flex">
        <input class="input-group border-dark me-auto mb-0 rounded-pill" style="padding-right:21rem; padding-left:2rem" type="search" placeholder="Search for anything" aria-label="Search" >
      </form>
      </ul>
      <ul class="navbar-nav me-0 mb-2 mb-lg-0">
        <li class="nav-item me-1">
          <a class="nav-link active" aria-current="page" href="#">Udemy Business</a>
        </li>
        <li class="nav-item me-1">
          <a class="nav-link active" aria-current="page" href="#">Teach on Udemy</a>
        </li>
        <li class="nav-item me-1">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="40" fill="currentColor" class="bi bi-cart3 me-2" viewBox="0 0 16 16">
  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
</svg>
        </li>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
           <button class="btn rounded-0 border-dark btn-outline-light me-md-2" type="button">
           <%= link_to "Login", new_user_session_path, class:"text-decoration-none", style:"color:black" %>
           </button>
           <button class="btn rounded-0 btn-dark me-md-2" type="button">
           <%= link_to "Signup", new_user_registration_path, class:"text-decoration-none", style:"color:white" %>
           </button></button>
           <br>
           <button class="btn rounded-0 border-dark btn-outline-light me-md-2" type="button">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" style="color:black" height="20" fill="currentColor" class="bi bi-globe" viewBox="0 0 16 16">
  <path d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm7.5-6.923c-.67.204-1.335.82-1.887 1.855A7.97 7.97 0 0 0 5.145 4H7.5V1.077zM4.09 4a9.267 9.267 0 0 1 .64-1.539 6.7 6.7 0 0 1 .597-.933A7.025 7.025 0 0 0 2.255 4H4.09zm-.582 3.5c.03-.877.138-1.718.312-2.5H1.674a6.958 6.958 0 0 0-.656 2.5h2.49zM4.847 5a12.5 12.5 0 0 0-.338 2.5H7.5V5H4.847zM8.5 5v2.5h2.99a12.495 12.495 0 0 0-.337-2.5H8.5zM4.51 8.5a12.5 12.5 0 0 0 .337 2.5H7.5V8.5H4.51zm3.99 0V11h2.653c.187-.765.306-1.608.338-2.5H8.5zM5.145 12c.138.386.295.744.468 1.068.552 1.035 1.218 1.65 1.887 1.855V12H5.145zm.182 2.472a6.696 6.696 0 0 1-.597-.933A9.268 9.268 0 0 1 4.09 12H2.255a7.024 7.024 0 0 0 3.072 2.472zM3.82 11a13.652 13.652 0 0 1-.312-2.5h-2.49c.062.89.291 1.733.656 2.5H3.82zm6.853 3.472A7.024 7.024 0 0 0 13.745 12H11.91a9.27 9.27 0 0 1-.64 1.539 6.688 6.688 0 0 1-.597.933zM8.5 12v2.923c.67-.204 1.335-.82 1.887-1.855.173-.324.33-.682.468-1.068H8.5zm3.68-1h2.146c.365-.767.594-1.61.656-2.5h-2.49a13.65 13.65 0 0 1-.312 2.5zm2.802-3.5a6.959 6.959 0 0 0-.656-2.5H12.18c.174.782.282 1.623.312 2.5h2.49zM11.27 2.461c.247.464.462.98.64 1.539h1.835a7.024 7.024 0 0 0-3.072-2.472c.218.284.418.598.597.933zM10.855 4a7.966 7.966 0 0 0-.468-1.068C9.835 1.897 9.17 1.282 8.5 1.077V4h2.355z"/>
</svg>
</button>
           
        </div>
      
        <% end %>
        
      </ul>
    </div>
  </div>
</nav>

app/views/videos/edit.html.erb
<%= render "nav" %>
<h1>Edit Video</h1>
<%= render "form", video: @video %>
<%= render "foot" %>

app/views/videos/index.html.erb
<%= render "nav"%>

<% if user_signed_in? %>
<h1 style="text-align:center">Total Videos</h1>
<% if @videos.size!=0 %>
<ul>
  <% @videos.each do |video| %>
    <li>
        <%= link_to video.title, course_video_path(video.course_id, video) %>
    </li>
  <% end %>
</ul>
<% else %>
<h3 style="text-align:center; color:red">Oops!!! It seems that user has not added any videos here....</h3>
<p style="text-align:center;">Go to <%= link_to "Home", root_path , class:"text-decoration-none"%></p>
<% end %>
<% else %>
<h1 style="text-align:center">Total Videos</h1>
<ul>
  <% @videos.each do |video| %>
    <li>
        <%= link_to video.vid_title, course_video_path(video.course_id, video) %>
    </li>
  <% end %>
<%= link_to "Add Video", new_course_video_path(@course)%> 
<% end %>

<%
=begin%>
 <h1 style="text-align:center">

My Courses</h1>
 <ul>
  <% @reqcourse.each do |course| %>
    <li>
        <%= link_to course.course_name, course %>
    </li>
  <% end %>
</ul>
<h3><%= link_to "New Course", new_course_path %></h3>
<% else %>
<h1 style="text-align:center">Total Courses</h1>
<ul>
  <% @courses.each do |course| %>
    <li>
        <%= link_to course.course_name, course %>
    </li>
  <% end %>
</ul>

<h1 style="text-align:center; padding:auto"><%= link_to "Login", new_user_session_path, class:"text-decoration-none"%> to enroll</h1>
<% end %>
<%= render "foot" %> 
<%
=end
%>

app/views/videos/new.html.erb
<%= render "nav" %>
<p class="fs-3 pt-3 pb-2 me-3 d-grid col-md-3 offset-md-4 fw-bold" style="text-align:center" >New Video</p>
<hr class="d-grid col-md-3 offset-md-4 fw-bold">
<%= render "form" %>
<%= render "foot" %>

app/views/videos/show.html.erb
<%= render "nav" %>
<% if user_signed_in?  %>
<h2>Title: </h2><%= @video.title %>
<h2> Url: </h2><%= @video.url %>
<ul>
  <li><%= link_to "Home", root_path%>
</ul>
<% else %>
<h2>Title: </h2><%= @video.vid_title %>
<h2> Url: </h2><%= @video.url %>
<ul>
  <li>
  <%= link_to "Edit", edit_course_video_path(@course, @video) %>  | <%= link_to "Home", root_path%> | 
  <%= link_to "Delete", course_video_path(@course),
                  method: :delete,
                  data: { confirm: "Are you sure" } %></li>
</ul> 
<% end %>
<%= render "foot" %>