config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :order_items
  resources :carts 
  resources :courses do
   resources :videos
  end
  root 'courses#home'
  get 'carts/show'
  get '/courses/my_enroll/:id', to: 'courses#create', as:'enroll_regist'
  get '/courses/enroll/:id', to: 'enrollments#create', as:'enroll_course'
  get 'cart/checkout', to:'carts#checkout', as:'checkout'
  post 'courses/add_to_cart/:id', to:'courses#add_to_cart', as: 'add_to_cart'
  delete 'courses/remove_from_cart/:id', to:'courses#remove_from_cart', as:'remove_from_cart'
  devise_for :users
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    def show
        @order_items=current_order.order_items
      end
      def checkout
        if user_signed_in?
          @order_items=current_order.order_items
         for i in @order_items
          Enrollment.create(watched_videos: i.course.total_videos, user_id: current_user.id,course_id: i.course.id)
         end
        end
        @order_items.clear
        redirect_to courses_path
        # render 'carts/final'
      end
      def destroy
        @cart = @current_cart
        @cart.destroy
        session[:cart_id] = nil
        redirect_to root_path
      end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items with value of #{current_order.subtotal }$", carts_show_path %>

app/views/carts/_cart_item.html.erb
<%= render 'courses/nav' %>
<h1 style="text-align:center">Shopping Cart</h1>
<%
=begin%>
 <% if @cart.empty? %>
<h3 style="color:red">Please add item to cart</h3>
<% else %>
<ul>
  <% @cart.each do |cart| %>
    <li>
        <%= link_to cart.course_name %>
    </li>
  <% end %>
  <%= link_to "Checkout", checkout_path , class: "btn btn-primary btn-lg mt-4"%>
</ul>
<% end %> 
<%
=end%>
<% if @order_items.empty? %>
  <h3 style="color:red">Please add item to cart</h3>
<% else %>
  <ul style="display:flex; flex-wrap:wrap;">
    <% @order_items.each do |cart| %>
    <div class="card me-4 mb-3" style="width:18rem;">
      <%= link_to(image_tag(cart.course.image.thumb.url, alt: 'Image',:size => "286x180"), cart.course.image.url, target: '_blank') if cart.course.image? %>
     <div class="card-body">
      <h5 class="card-title"><%= link_to cart.course.course_name, style:"text-decoration:none;"%></h5>
      <p class="card-text"><%= cart.course.description %></p>
      <%= form_for cart, remote: true do |f| %>
        <%= link_to "Remove Items", order_item_path(cart), method: :delete, remote: true, class: "btn btn-primary mb-0 ms-5",style:"float:bottom;"%>
      <% end %>
     </div>
    </div>
    <% end %>
  </ul>
<% end %>
  <h3 style="color:red">Total Cost:<%= current_order.subtotal%></h3>
  <% if @order_items.size!=0%>
    <%= link_to "Checkout", checkout_path, class: "btn btn-primary btn-lg mt-4 ms-5"%>
  <% end %>
<%= render 'courses/foot'  %>

app/views/carts/final.html.erb
<h1>We r in</h1>

app/views/carts/show.html.erb
<%
=begin%>
 <%= render 'courses/nav' %>
<h1 style="text-align:center">Shopping Cart</h1>
 <% if @cart.empty? %>
<h3 style="color:red">Please add item to cart</h3>
<% else %>
<ul>
  <% @cart.each do |cart| %>
    <li>
        <%= link_to cart.course_name %>
    </li>
  <% end %>
  <%= link_to "Checkout", checkout_path , class: "btn btn-primary btn-lg mt-4"%>
</ul>
<% end %> 
 <div class="cart">
<%= render 'carts/cart' %>
</div> 
<%= render 'courses/foot'  %>
 
<%
=end%>

<div class="cart-item">
<%= render 'cart_item' %>
</div> 