config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :order_items
  resources :carts 
  resources :courses do
   resources :videos
  end
  root 'courses#home'
  get 'carts/show'
  get '/courses/my_enroll/:id', to: 'courses#create', as:'enroll_regist'
  get '/courses/enroll/:id', to: 'enrollments#create', as:'enroll_course'
  get 'cart/checkout', to:'carts#checkout', as:'checkout'
  post 'courses/add_to_cart/:id', to:'courses#add_to_cart', as: 'add_to_cart'
  delete 'courses/remove_from_cart/:id', to:'courses#remove_from_cart', as:'remove_from_cart'
  devise_for :users
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    # before_action :initialize_session
    # before_action :load_cart
    def home
        @courses=Course.all
    end 
       # def add_to_cart
       #  id=params[:id].to_i
       #  @cart = Course.find(session[:cart])
       #  session[:cart] << id unless session[:cart].include?(id)
       #  redirect_to course_path(id)
       # end
       # def remove_from_cart
       #  id=params[:id].to_i
       #  session[:cart].delete(id)
       #  redirect_to root_path
       # end
       # def initialize_session
       #  session[:cart] ||=[]
       # end 
       # def load_cart
       #  @cart=Course.find(session[:cart])
       # end 
       
        def index
        @courses=Course.all
        if user_signed_in?
         @enroll=Enrollment.where(user_id: current_user.id).distinct.to_a
         @courses=Course.all
         @reqcourse=[]
         for i in @enroll
           for j in @courses
            if j.id==i.course_id
             @reqcourse.push(j)
            end
           end
         end
         if current_user.user_role.downcase == "instructor"
           @usercourse=Course.where(user_id: current_user.id).to_a
         end 
        end
       #  @course=Course.find(3)
       #  @instructor=Instructor.find(@course.instructor_id)
        # @user=User.find(params[:id])
       end
       def show  
        @course=Course.find(params[:id])#1
        @videos=@course.videos     
        @order_item=current_order.order_items.new   
        if user_signed_in?
        #CartsController.addtocart(@course.id)#editted 
         @enroll=Enrollment.where(user_id: current_user.id).distinct.to_a
         @reqcourse=[]
         @allcourseid=[]
         @ordercourse=[]
         @order=current_order.order_items
         for i in @enroll
            if @course.id==i.course_id
             @reqcourse.push(@course.id)
            end
         end
         for i in @order
            @ordercourse.push(i.course.id)
         end
        end
        @instructor=User.find(@course.user_id)
       end
       def new
        @course=Course.new
       end
       def edit
        @course=Course.find(params[:id])
       end
       def update
        @course = Course.find(params[:id])
        if @course.update(course_params)
          redirect_to @course
        else
          render :edit
        end
       end
       def create
        # @course = Course.new(course_params)
       #  @inst = Instructor.find(params[:id])
        @course = Course.create(course_params)
        #@instructor.course=create_course_path(@instructors)
        if @course.save
          redirect_to @course
        else
          render :new
        end
       end
       def destroy
        @course=Course.find(params[:id])
        @course.destroy
        redirect_to root_path
       end
       private
        def course_params
          params.require(:course).permit(:course_name, :description, :total_videos, :duration, :cost,:category, :user_id,:image)
        end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_foot.html.erb
<nav class="navbar navbar-expand-lg d-flex navbar-light bg-white shadow p-0 mb-0 bg-body rounded">
<div class="bg-dark container-fluid" style="margin-top:24rem">
  <footer class="py-5 px-5 mt-5 pb-0" style="width:70rem">
    <div class="row">
        <h5 style="color:white">Top companies choose <%= link_to "Udemy Business", root_path%> to build in-demand career skills.</h5>
    </div>
    <div class="d-flex justify-content-between py-5 my-5 border-top" style="width:65rem;">
    <div class="col-2" style="color:white">
        <ul class="nav flex-column" style="color:white">
          <li class="nav-item mb-3"><a href="#" style="color:white" class="nav-link p-0 ">Udemy Business</a></li>
          <li class="nav-item mb-3"><a href="#" style="color:white" class="nav-link p-0 ">Teach on Udemy</a></li>
          <li class="nav-item mb-3"><a href="https://play.google.com/store/apps/details?id=com.udemy.android" style="color:white" class="nav-link p-0 ">Get the app</a></li>
          <li class="nav-item mb-3"><a href="#" style="color:white" class="nav-link p-0 ">About us</a></li>
          <li class="nav-item mb-3"><a href="#" style="color:white" class="nav-link p-0">Contact us</a></li>
        </ul>
      </div>
      <div class="col-2">
        <ul class="nav flex-column">
          <li class="nav-item mb-3"><a href="#" style="color:white" class="nav-link p-0 ">Careers</a></li>
          <li class="nav-item mb-3"><a href="#" style="color:white" class="nav-link p-0 ">Blog</a></li>
          <li class="nav-item mb-3"><a href="#" style="color:white" class="nav-link p-0 ">Help and Support</a></li>
          <li class="nav-item mb-3"><a href="#" style="color:white" class="nav-link p-0 ">Affiliate</a></li>
          <li class="nav-item mb-3"><a href="#" style="color:white" class="nav-link p-0 ">Investors</a></li>
        </ul>
      </div>

      <div class="col-2">
        <ul class="nav flex-column">
          <li class="nav-item mb-3"><a href="#" style="color:white" class="nav-link p-0 ">Terms</a></li>
          <li class="nav-item mb-3"><a href="#" style="color:white" class="nav-link p-0 ">Privacy Policy</a></li>
          <li class="nav-item mb-3"><a href="#" style="color:white" class="nav-link p-0 ">Sitemap</a></li>
          <li class="nav-item mb-3"><a href="#" style="color:white" class="nav-link p-0 ">Accessibility Statements</a></li>
        </ul>
      </div>
      <div class="col-4 offset-5 text-decoration-none">
        <form>
          <div class="">
            <button class="btn rounded-0 border-light btn-outline-secondary text-decoration-none" type="button" style="color:white">Subscribe</button>
          </div>
        </form>
      </div>
      <%
=begin%>
 <p>© 2021 Company, Inc. All rights reserved.</p>
      <ul class="list-unstyled d-flex">
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
      </ul> 
<%
=end%>
    </div>
  </footer>
</div>
</nav>

app/views/courses/_nav.html.erb
<% if user_signed_in? %>
<% if current_user.user_role.downcase == "student"%>
<nav class="navbar navbar-expand-lg d-flex navbar-light bg-white shadow  p-3 mb-0 bg-body rounded">
  <div class="container-fluid mt-0" >
    <h1 class="navbar-brand fw-bold"><%= link_to "UdemyClone", root_path , class:"text-decoration-none ", style:"color:black"%></h1>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Categories</a>
        </li>
        <form class="d-flex">
        <input class="input-group border-dark me-auto mb-0 rounded-pill" style="padding-right:21rem; padding-left:2rem" type="search" placeholder="Search for anything" aria-label="Search" >
      </form>
      </ul>
      <ul class="navbar-nav me-1 mb-2 mb-lg-0">
        <li class="nav-item me-4">
          <a class="nav-link active" aria-current="page" href="#">Udemy Business</a>
        </li>
        <li class="nav-item me-4 mt-2">
         <%= link_to "My Learning", courses_path, class:"text-decoration-none ", style:"color:black"%>
        </li>
        <li class="nav-item me-4 ms-2 mt-2">
        <%= link_to "Cart",carts_show_path ,class:"text-decoration-none",style:"color:black"%>
        <%
=begin%>
 <svg xmlns="http://www.w3.org/2000/svg" width="20" height="40" fill="currentColor" class="bi bi-cart3 me-2" viewBox="0 0 16 16">
  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
</svg> 
<%
=end%>
        </li>
        
        <li class="nav-item me-2">
        <div class="btn-group">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%
=begin%>
 <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-person-circle pe-2" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg> 
<%
=end%>
           <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
           <%= link_to current_user.name, "destroy_user_session_path", class:"text-decoration-none ", style:"color:white"%>
          </button>
           <ul class="dropdown-menu">
    <li><%= link_to "My Learning", courses_path,class:"text-decoration-none dropdown-item", style:"color:black"%></li>
    <li><%= link_to "My Cart",carts_show_path ,class:"text-decoration-none dropdown-item",style:"color:black"%></li>
    <li><a class="dropdown-item" href="#">Dashboard</a></li>
    <li><a class="dropdown-item" href="#">Notification</a></li>
    <li><a class="dropdown-item" href="#">Messages</a></li>
    <li><a class="dropdown-item" href="#">Account</a></li>
    <li><%= link_to "Edit Profile", edit_user_registration_path,class:"text-decoration-none dropdown-item", style:"color:black"%></li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete ,class:"text-decoration-none dropdown-item", style:"color:black"%></li>
  </ul>
        </div>
        </div>
        
        </li>
        <% elsif current_user.user_role.downcase == "instructor"%>
  <nav class="navbar navbar-expand-lg d-flex navbar-light bg-white shadow p-3 mb-4 bg-body rounded">
  <div class="container-fluid mt-0">
    <h1 class="navbar-brand fw-bold" href="#"><%= link_to "UdemyClone", root_path , class:"text-decoration-none ", style:"color:black"%></h1>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Categories</a>
        </li>
        <form class="d-flex">
        <input class="input-group border-dark me-auto mb-0 rounded-pill" style="padding-right:21rem; padding-left:2rem" type="search" placeholder="Search for anything" aria-label="Search" >
      </form>
      </ul>
      <ul class="navbar-nav me-0 mb-2 mb-lg-0">
        <li class="nav-item me-1">
          <a class="nav-link active" aria-current="page" href="#">Udemy Business</a>
        </li>
        <li class="nav-item me-1">
          <a class="nav-link active" aria-current="page" href="#">Teach on Udemy</a>
        </li>
        <li class="nav-item me-3 ms-2 mt-2">
        <%= link_to "My Course",courses_path ,class:"text-decoration-none",style:"color:black"%>
        <%
=begin%>
 <svg xmlns="http://www.w3.org/2000/svg" width="20" height="40" fill="currentColor" class="bi bi-cart3 me-2" viewBox="0 0 16 16">
  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
</svg> 
<%
=end%>
        </li>
        
        <li class="nav-item me-2">
        <div class="btn-group">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%
=begin%>
 <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-person-circle pe-2" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg> 
<%
=end%>
           <button class="btn btn-dark dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
           <%= link_to current_user.name, "destroy_user_session_path", class:"text-decoration-none ", style:"color:white"%>
          </button>
           <ul class="dropdown-menu">
    <li><%= link_to "My Course", courses_path,class:"text-decoration-none dropdown-item", style:"color:black"%></li>
    <li><a class="dropdown-item" href="#">Dashboard</a></li>
    <li><a class="dropdown-item" href="#">Notification</a></li>
    <li><a class="dropdown-item" href="#">Messages</a></li>
    <li><a class="dropdown-item" href="#">Account</a></li>
    <li><a class="dropdown-item" href="#">Edit Profile</a></li>
    <li><%= link_to "Logout", destroy_user_session_path, method: :delete ,class:"text-decoration-none dropdown-item", style:"color:black"%></li>
  </ul>
        </div>
        </div>
        </li>
        <% end %>
        <% else %>
        <nav class="navbar navbar-expand-lg d-flex navbar-light bg-white shadow p-3 mb-4 bg-body rounded">
  <div class="container-fluid mt-0">
    <h1 class="navbar-brand fw-bold" href="#"><%= link_to "UdemyClone", root_path , class:"text-decoration-none", style:"color:black"%></h1>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Categories</a>
        </li>
        <form class="d-flex">
        <input class="input-group border-dark me-auto mb-0 rounded-pill" style="padding-right:21rem; padding-left:2rem" type="search" placeholder="Search for anything" aria-label="Search" >
      </form>
      </ul>
      <ul class="navbar-nav me-0 mb-2 mb-lg-0">
        <li class="nav-item me-1">
          <a class="nav-link active" aria-current="page" href="#">Udemy Business</a>
        </li>
        <li class="nav-item me-1">
          <a class="nav-link active" aria-current="page" href="#">Teach on Udemy</a>
        </li>
        <li class="nav-item me-1">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="40" fill="currentColor" class="bi bi-cart3 me-2" viewBox="0 0 16 16">
  <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
</svg>
        </li>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
           <button class="btn rounded-0 border-dark btn-outline-light me-md-2" type="button">
           <%= link_to "Login", new_user_session_path, class:"text-decoration-none", style:"color:black" %>
           </button>
           <button class="btn rounded-0 btn-dark me-md-2" type="button">
           <%= link_to "Signup", new_user_registration_path, class:"text-decoration-none", style:"color:white" %>
           </button></button>
           <br>
           <button class="btn rounded-0 border-dark btn-outline-light me-md-2" type="button">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" style="color:black" height="20" fill="currentColor" class="bi bi-globe" viewBox="0 0 16 16">
  <path d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm7.5-6.923c-.67.204-1.335.82-1.887 1.855A7.97 7.97 0 0 0 5.145 4H7.5V1.077zM4.09 4a9.267 9.267 0 0 1 .64-1.539 6.7 6.7 0 0 1 .597-.933A7.025 7.025 0 0 0 2.255 4H4.09zm-.582 3.5c.03-.877.138-1.718.312-2.5H1.674a6.958 6.958 0 0 0-.656 2.5h2.49zM4.847 5a12.5 12.5 0 0 0-.338 2.5H7.5V5H4.847zM8.5 5v2.5h2.99a12.495 12.495 0 0 0-.337-2.5H8.5zM4.51 8.5a12.5 12.5 0 0 0 .337 2.5H7.5V8.5H4.51zm3.99 0V11h2.653c.187-.765.306-1.608.338-2.5H8.5zM5.145 12c.138.386.295.744.468 1.068.552 1.035 1.218 1.65 1.887 1.855V12H5.145zm.182 2.472a6.696 6.696 0 0 1-.597-.933A9.268 9.268 0 0 1 4.09 12H2.255a7.024 7.024 0 0 0 3.072 2.472zM3.82 11a13.652 13.652 0 0 1-.312-2.5h-2.49c.062.89.291 1.733.656 2.5H3.82zm6.853 3.472A7.024 7.024 0 0 0 13.745 12H11.91a9.27 9.27 0 0 1-.64 1.539 6.688 6.688 0 0 1-.597.933zM8.5 12v2.923c.67-.204 1.335-.82 1.887-1.855.173-.324.33-.682.468-1.068H8.5zm3.68-1h2.146c.365-.767.594-1.61.656-2.5h-2.49a13.65 13.65 0 0 1-.312 2.5zm2.802-3.5a6.959 6.959 0 0 0-.656-2.5H12.18c.174.782.282 1.623.312 2.5h2.49zM11.27 2.461c.247.464.462.98.64 1.539h1.835a7.024 7.024 0 0 0-3.072-2.472c.218.284.418.598.597.933zM10.855 4a7.966 7.966 0 0 0-.468-1.068C9.835 1.897 9.17 1.282 8.5 1.077V4h2.355z"/>
</svg>
</button>
           
        </div>
      
        <% end %>
        
      </ul>
    </div>
  </div>
</nav>

app/views/courses/edit.html.erb
<%= render "nav" %>
<h1>Edit Course</h1>
<%= render "form", course: @course %>
<%= render "foot" %>

app/views/courses/index.html.erb
<%= render "nav"%>
<% if user_signed_in? %>
  <% if current_user.user_role.downcase == "instructor"%>
     <h1 style="text-align:center; font-style:bolder">Created Courses</h1>
     <% if @usercourse.size==0 %>
       <h3 style="color:red">No Courses Created yet...</h3>Create new course <%= link_to "here", new_course_path, style:"text-decoration:none" %>
     <% else  %>
       <ul style="display:flex; flex-wrap:wrap;">
       <% @usercourse.each do |course| %>
         <% if course.user_id==current_user.id %>
           <div class="card me-4 mb-3" style="width:18rem;">
             
 <%= link_to(image_tag(course.image.thumb.url, alt: 'Image',:size => "286x180"), course.image.url, target: '_blank') if course.image? %> 
             <div class="card-body">
               <h5 class="card-title"><%= link_to course.course_name, course ,style:"text-decoration:none"%></h5>
               <p class="card-text"><%= course.description %></p>
             </div>
             <%= link_to "Go to course", course ,style:"text-decoration:none;", class:"btn btn-primary m-3"%>
           </div>
         <% end %>  
       <% end %>
       </ul>
       Create new course <%= link_to "here", new_course_path, style:"text-decoration:none"%>
     <% end %>
  <% else %>
    <h1 style="text-align:center">My Courses</h1>
    <ul style="display:flex; flex-wrap:wrap;">
    <% @reqcourse.each do |course| %>
      <div class="card me-4 mb-3" style="width:18rem;">
 <%= link_to(image_tag(course.image.thumb.url, alt: 'Image',:size => "286x180"), course.image.url, target: '_blank') if course.image? %> 
        <div class="card-body">
          <h5 class="card-title"><%= link_to course.course_name, course ,style:"text-decoration:none"%></h5>
          <p class="card-text"><%= course.description %></p>
        </div>
        <%= link_to "Go to course", course ,style:"text-decoration:none;", class:"btn btn-primary m-3"%>
      </div>
    <% end %>
    </ul> 
  <% end %> 
<% else %>
  <h1 style="text-align:center">Total Courses</h1>
    <% if @courses.size==0 %>
      <h3 style="color:red">No Courses Published yet...</h3>
    <% end %>
    <ul style="display:flex; flex-wrap:wrap;">
      <% @courses.each do |course| %>
        <div class="card" style="width: 18rem;">
          <img src="..." class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= link_to course.course_name, course %></h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
          <%= link_to "Go to course", course ,style:"text-decoration:none;", class:"btn btn-primary m-3"%> 
        </div>
  <% end %>
</ul>
<h1 style="text-align:center; padding:auto"><%= link_to "Login", new_user_session_path, class:"text-decoration-none"%> to enroll</h1>
<% end %>
<%= render "foot" %>

app/views/courses/new.html.erb
<%= render "nav" %>
<h1>New Course</h1>
<%= render "form", course: @course %>
<%= render "foot" %>

app/views/courses/show.html.erb
<%= render "nav" %>
<% if user_signed_in?  %>
  <% if (current_user.user_role.downcase =="instructor" && @course.user_id==current_user.id) %>
 <%= link_to(image_tag(@course.image.thumb.url, alt: 'Image',:size => "286x180"), @course.image.url, target: '_blank') if @course.image? %>  
      <h2>Description: </h2><%= @course.description %></h2>
      <h2> Category: </h2><%= @course.category %></h2>
      <h2> Cost: </h2><%= @course.cost %></h2>
      <h2>Duration: </h2><%= @course.duration %></h2>
      <h2>Instructor: </h2><%= @instructor.name %></h2>
      <h3>
        <%= link_to "Videos", course_videos_path(@course) , class:"btn btn-primary ms-2"%> 
        <%= link_to "Home", root_path, class:"btn btn-primary ms-2"%>
        <%= link_to "Add Video",new_course_video_path(@course),class:"btn btn-primary ms-2"%>
        <%= link_to "Edit", edit_course_path(@course),class:"btn btn-primary ms-2"%>
        <%= link_to "Delete", course_path(@course),method: :delete,data: { confirm: "Are you sure" } , class:"btn btn-primary ms-2"%> 
      </h3>
  <% else %>
    <% if @reqcourse.include? @course.id %>
      
 <%= link_to(image_tag(@course.image.thumb.url, alt: 'Image',:size => "286x180"), @course.image.url, target: '_blank') if @course.image? %>  
      <h2>Description: </h2><%= @course.description %></h2>
      <h2> Category: </h2><%= @course.category %></h2>
      <h2> Cost: </h2><%= @course.cost %></h2>
      <h2>Duration: </h2><%= @course.duration %></h2>
      <h2>Instructor: </h2><%= @instructor.name %></h2><br>
      <h3><%= link_to "Videos", course_videos_path(@course) , class:"btn btn-primary ms-2"%> 
      <%= link_to "Home", root_path, class:"btn btn-primary ms-2"%>
      </h3>
    <% else %>
 <%= link_to(image_tag(@course.image.thumb.url, alt: 'Image',:size => "286x180"), @course.image.url, target: '_blank') if @course.image? %>  

      <h2>Description: </h2><%= @course.description %></h2>
      <h2> Category: </h2><%= @course.category %></h2>
      <h2> Cost: </h2><%= @course.cost %></h2>
      <h2>Duration: </h2><%= @course.duration %></h2>
      <h2>Instructor: </h2><%= @instructor.name %></h2>
      <ul>
        <% if @ordercourse.include?(@course.id) %>
          <%= link_to "Go to Cart",carts_show_path ,class:"btn btn-primary"%>
        <% else %> 
          <%= form_for @order_item, remote: true do |f|  %>
            <%= f.hidden_field :course_id, :value => @course.id%>
            <%= link_to "Home", root_path, class:"btn btn-primary"%> 
            <%= f.submit "Add to new cart" ,class:"btn btn-primary"%>
          <% end %>
        <% end %>
      </ul>
    <% end %> 
  <% end %>
<% else %>
  
 <%= link_to(image_tag(@course.image.thumb.url, alt: 'Image',:size => "286x180"), @course.image.url, target: '_blank') if @course.image? %>  
  <h2>Description: </h2><%= @course.description %></h2>
  <h2> Category: </h2><%= @course.category %></h2>
  <h2> Cost: </h2><%= @course.cost %></h2>
  <h2>Duration: </h2><%= @course.duration %></h2>
  <h2>Instructor: </h2><%= @instructor.name %></h2>
<%
=begin%>
 <ul>
  <li><%= link_to "Edit", edit_course_path(@course) %> | <%= link_to "Home", root_path%> | <%= link_to "Delete", course_path(@course),
                  method: :delete,
                  data: { confirm: "Are you sure" } %> 
                   </li>
</ul> 
<%
=end%>
<% end %>
<%= render "foot" %>